### ISSUE TITLE
Routes, Scopes, Usage Multilang t in routes

### ISSUE THREAD

**Issue by Destilate** [akalongman/laravel-multilang#13]
I am trying to use your multilang package for laravel, and now i am trying to find way how to use it in the routes with scope and in another place with another scope.

I want use t('something') as url for example:

Route::get(t('something')."/".t('something2'), '\Modules\Page\Http\Controllers\Front\PageController@index')->name('welcome');

i need for usage in the routes another scope (use scopes as categories for better recognizing)

i tried app('multilang')->setScope('admin'); for routes before Multilang routes

and another inside controller

app('multilang')->setScope('sitel');
        
$text = t('test');

but only last aplied (global)

Please can u tell me how i can create groups of texts with scope, or how to use scope properly.

**Comment by akalongman** [comment]
> I want use t('something') as url for example:
> 
> Route::get(t('something')."/".t('something2'), '\Modules\Page\Http\Controllers\Front\PageController@index')->name('welcome');

Its a bad practice, dont do this. Explain to me what you want to achieve and maybe I can suggest better solution

> i need for usage in the routes another scope (use scopes as categories for better recognizing)
> but only last aplied (global)

I will check, maybe its a bug

**Comment by Destilate** [comment]
I want use it for multilanguage routing

for example:

http://web.com/en/welcome
http://web.com/de/wilkome

http://web.com/{lang}/name-of-route-in-{lang}-language

something like this, but you wrote it is not good practise:

MultiLang::routeGroup(function($router) {
Route::get(t('language-identifikator-of-route-for-all-language'), '\Modules\Page\Http\Controllers\Front\PageController@index')->name('welcome');
});
