### ISSUE TITLE
Unable to exclude the admin urls from Multilang

### ISSUE THREAD

**Issue by HarisTechverx** [akalongman/laravel-multilang#14]
Can you please guide me how can I exclude some of the urls that I dont want translated?

All the routes are being redirected automatically to en/route. I need to Exclude all the admin routes from multilang. I can see the exclude segment array in config , how can I use it?

**Comment by akalongman** [comment]
@HarisTechverx you can exclude routes like this:

```php
    'exclude_segments'  => [
        '_debugbar/*',
        '_dusk/*',
        'url*',
        'api/*',
    ],
```

**Comment by HarisTechverx** [comment]
@akalongman I have added this but it is still not working.
` /*
    |--------------------------------------------------------------------------
    | Set System locale
    |--------------------------------------------------------------------------
    |
    | Call setlocale(LC_ALL, $locale) and set current locale in middleware
    |
     */
    'set_system_locale' => false,

    /*
    |--------------------------------------------------------------------------
    | Exclude segments from redirect
    |--------------------------------------------------------------------------
    |
    | Exclude segments from redirects in the middleware
    |
     */
    'exclude_segments'  => [
        '/admin/*',
    ],`

**Comment by HarisTechverx** [comment]
@akalongman Can you please help me here? I am really stuck here.

**Comment by akalongman** [comment]
@HarisTechverx is your project online? Can I access the web site?

**Comment by iharden** [comment]
@HarisTechverx I resolved this problem when i wrote uri without another rules:
'exclude_segments'  => [
        'admin',
    ],

**Comment by akalongman** [comment]
@HarisTechverx is your problem solved?

**Comment by GodlikeBasic** [comment]
It's work for Nova admin panel

```
'exclude_segments'  => [
        'nova/*',
        'nova-api/*',
        'nova-vendor/*'
    ],
```

Version with slash not working
```
'exclude_segments'  => [
        '/nova/*',
    ],
```
