### ISSUE TITLE
Is there a way to hide current lang in url?

### ISSUE THREAD

**Issue by ivy47** [akalongman/laravel-multilang#15]
Is possible to hide lang in url? For example my current url looks like domain.com/ru, is there a way to make it looks like domain.com/ ?

**Comment by akalongman** [comment]
@ivy47 how you will recognize current language?

**Comment by ivy47** [comment]
Maybe some kind of database configuration, which depends on the current user or session / cookie?

**Comment by akalongman** [comment]
@ivy47 just do not use `LaravelMultiLangMiddleware`

**Comment by ivy47** [comment]
@akalongman  Ok, i got it. Thanks for the quick reply.
