### ISSUE TITLE
Need help with testing and maintaining project

### ISSUE THREAD

**Issue by akalongman** [akalongman/laravel-multilang#3]
I need help with testing and maintaining project. This project has future and I need help with improving

**Comment by marttosc** [comment]
What do you need to test, specifically?

**Comment by akalongman** [comment]
Is it useful package for easy creating multi language web applications on Laravel? If not, what we need to add/remove from this package?

**Comment by marttosc** [comment]
@akalongman have you seen the PR?

**Comment by akalongman** [comment]
Merged, thank you! 
> What do you need to test, specifically?
We need test it on new Laravel 5.3, also think how implement page for managing texts (something like laravel-passport which has small "admin panel" for managing tokens)

**Comment by akalongman** [comment]
Also we need increase test coverage
