### ISSUE TITLE
helper function to generate url in different language

### ISSUE THREAD

**Issue by thecotne** [akalongman/laravel-multilang#6]
something like this

```blade
{{ current_url_in_different_language('ka') }}
```

you need to come up with good name for this

**Comment by thecotne** [comment]
may be add second parameter to `lang_url` ? (but this solves other problem :D )

**Comment by akalongman** [comment]
It's done via `lang_url` function (added 4th parameter): https://github.com/akalongman/laravel-multilang/blob/master/src/helpers.php#L21
